-- MySQL Script generated by MySQL Workbench
-- Mon Dec 19 10:53:00 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema hiring
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hiring
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hiring` DEFAULT CHARACTER SET utf8 COLLATE utf8_turkish_ci ;
USE `hiring` ;

-- -----------------------------------------------------
-- Table `hiring`.`alanlar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hiring`.`alanlar` (
  `alan_id` (11) NOT NULL,
  `alan_adi` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`alan_id`),
  UNIQUE INDEX `alan_id_UNIQUE` (`alan_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hiring`.`cv`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hiring`.`cv` (
  `cv_id` (11) NOT NULL,
  `cv_kullanici_id` VARCHAR(45) NOT NULL,
  `cv_dosya_yolu` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cv_id`),
  UNIQUE INDEX `cv_id_UNIQUE` (`cv_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hiring`.`diller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hiring`.`diller` (
  `dil_id` (11) NOT NULL,
  `dil_adi` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`dil_id`),
  UNIQUE INDEX `dil_id_UNIQUE` (`dil_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hiring`.`fotograflar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hiring`.`fotograflar` (
  `fotograf_id` (11) NOT NULL,
  `fotograf_dosya_yolu` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`fotograf_id`),
  UNIQUE INDEX `fotograf_id_UNIQUE` (`fotograf_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hiring`.`iletisim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hiring`.`iletisim` (
  `iletisim_id` (11) NOT NULL,
  `iletisim_telefon_no` (11) NOT NULL,
  `iletisim_mail_adresi` VARCHAR(45) NOT NULL,
  `iletisim_adres` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iletisim_id`),
  UNIQUE INDEX `iletisim_id_UNIQUE` (`iletisim_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hiring`.`isverenler`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hiring`.`isverenler` (
  `isveren_id` (11) NOT NULL,
  PRIMARY KEY (`isveren_id`),
  UNIQUE INDEX `isveren_id_UNIQUE` (`isveren_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hiring`.`kullanicilar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hiring`.`kullanicilar` (
  `kullanici_id` (11) NOT NULL,
  `kullanici_ad` VARCHAR(45) NOT NULL,
  `kullanici_soyad` VARCHAR(45) NOT NULL,
  `kullanici_tanitim` VARCHAR(45) NOT NULL,
  `kullanici_teklife_acik_mi` (4) NOT NULL,
  PRIMARY KEY (`kullanici_id`),
  UNIQUE INDEX `kullanici_id_UNIQUE` (`kullanici_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hiring`.`meslekler`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hiring`.`meslekler` (
  `meslek_id` (11) NOT NULL,
  `meslek_adi` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`meslek_id`),
  UNIQUE INDEX `meslek_id_UNIQUE` (`meslek_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hiring`.`sirketler`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hiring`.`sirketler` (
  `sirket_id` (11) NOT NULL,
  `sirket_adi` VARCHAR(45) NOT NULL,
  `sirket_vizyon` VARCHAR(100) NULL DEFAULT NULL,
  `sirket_misyon` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`sirket_id`),
  UNIQUE INDEX `sirket_id_UNIQUE` (`sirket_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hiring`.`videolar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hiring`.`videolar` (
  `video_id` (11) NOT NULL,
  `video_adi` VARCHAR(45) NOT NULL,
  `video_basligi` VARCHAR(45) NOT NULL,
  `video_zamani` (11) NOT NULL,
  PRIMARY KEY (`video_id`),
  UNIQUE INDEX `video_id_UNIQUE` (`video_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
